kind: pipeline
type: docker
name: deploy

trigger:
  branch:
    - main
  event:
    - push

clone:
  depth: 1

steps:
  - name: 检查环境版本
    image: node:22-alpine
    pull: always
    commands:
      - node -v
      - npm -v
      - apk add git

  - name: 安装项目依赖
    image: node:22-alpine
    pull: always
    commands:
      - npm install -g pnpm
      - pnpm install --frozen-lockfile
    volumes:
      - name: pnpm-store
        path: /drone/src/.pnpm-store

  - name: 构建项目
    image: node:22-alpine
    pull: always
    commands:
      - pnpm run build
    volumes:
      - name: pnpm-store
        path: /drone/src/.pnpm-store

  - name: 部署到服务器
    image: node:22-alpine
    pull: always
    commands:
      - cp -r dist/* /opt/1panel/apps/openresty/openresty/www/sites/tazmi.online/index/
    volumes:
      - name: website
        path: /opt/1panel/apps/openresty/openresty/www/sites/tazmi.online/index/

  - name: 发送通知
    image: alpine:latest
    pull: always
    commands:
      - echo "部署完成,时间: $(date)"
    when:
      status:
        - success

volumes:
  - name: pnpm-store
    host:
      path: /tmp/drone-pnpm-store
  - name: website
    host:
      path: /opt/1panel/apps/openresty/openresty/www/sites/tazmi.online/index/